### ISSUE TITLE
First version online

### ISSUE THREAD

**Issue by knacker** [kulkeeli/Blau-Weiss-Eichwege-SV#5]
As you may have noticed, we already have a working(kinda) version of the website. Do you have any suggestions or improvements that could be made? (Since the Blue backround color didn't look that nice, we have changed it to green; that looked better for now)

**Comment by kulkeeli** [comment]
Hello,

I will not give you a full review since we need some points for the next assingment but I can give you some suggestions in reference to the requirements.

-  The border of the logo was meant to only frame the logo and not the whole SVG. Similar to the blue border in the logo of TSG 1899 Hoffenheim but without the white border. Also make the border more thick. 

- Please only use colors we have provided. Do not use any non-neutral color other than these two blues since these are our identifcation color. Also do not use black. If you need a third neutral color we can give you one. 

- In general you barely use the neutral colors for your design. This is not necessarily a bad thing but, for example, if you don't think a blue background would work you can make it neutral and use that blue more subtle in text or tables as they are very plain so far. A lot of websites only use neutral backgrounds so they can use their other colors on other style elements. You can look at those if you need inspiration. 

- The butons do not look like buttons so far. Use a persistent background for them. 

- Do not use rounded corners for the background

- Make sure to only use our fonts and in the way we have intended

**Comment by IchBinMuffin** [comment]
First of all thanks for the answer!

- A frame and a border are two different things. As it is described in the README file, the whole logo should be framed. We will now change it so that the border shows off the crest the way you want it to be

- The colors used are not final yet and will be changed to the desired colors soon. We will try to use all colors suitable. However, the colors could be far from a modern website and make the overall image look rather "cheap". In this case we would consult your opinion again and possibly reconsider the color scheme finally

- We will change the buttons and the wrapper so that it corresponds to your ideas

- We just used your fonts. Unfortunately there is a problem with some browsers, which causes the fonts to be replaced with "Arial"

If there are more suggestions on your site, feel free to contact us, so we can implement the changes according to your ideas.

**Comment by kulkeeli** [comment]
Alright. Thank you. Sorry, if the instructions sometimes were unclear.

In case of the colors try to make a modern look. Then, we can give you our opinion in the next assignment.   

I have visited the website using Firefox and did not see the fonts.

One thing I forgot to mention: We wanted to change the link with the video. So the link should not be on the website anymore and the video should be visible on the page 'About Eichwege'. Again, we apologize if this was a bit confusing.

**Comment by IchBinMuffin** [comment]
We have changed the website according to your mentioned points and only used your colors. You can have a look and say, if this fits to your expectations

**Comment by kulkeeli** [comment]
One last change: Please set the opacity of the blue background to 50%. 

Thank you,

**Comment by knacker** [comment]
We set the opacity to 50% now, although it doesn't look good if you ask me. We can discuss the changes again in part c if you don't like it.
